export const homeObjOne = {
	id: 'about',
	lightBg: false,
	lightText: false,
	lightTextDesc: true,
	lightTextTop: true,
	topLine: 'Empeza a estudiar de manera autodidacta',
	headline: 'Busca información',
	description: '',
	buttonLabel: 'Contacto',
	imgStart: true,
	img: require('../../images/svg1.svg').default,
	alt: 'image',
	dark:true,
	primary: true,
	darkText: false,
	start: '',
}
export const homeObjTwo = {
	id: 'discover',
	lightBg: true,
	lightText: true,
	lightTextDesc: true,
	lightTextTop: true,
	topLine: 'Tecnologías más utilizadas en el mercado It',
	headline: 'Html, Css, Javascript, React y más ...',
	description: 'Mi hoja de ruta para aprender hacer sitios web como este.',
	buttonLabel: 'Enviar un mensaje',
	imgStart: false,
	img: require('../../images/svg2.svg').default,
	alt: 'Paper',
	dark: false,
	primary: false,
	darkText: false,
	start: 'true',
}
export const homeObjThree = {
	id: 'signup',
	lightBg: false,
	lightText: false,
	lightTextDesc: false,
	lightTextTop: true,
	topLine: 'Jonatan Cristian Ochoa',
	headline: 'DESARROLLADOR WEB FRONT-END',
	description: 'Desarrollo de paginas web estáticas y dinámicas con React JS, además implementacion de una base de datos en Firestore para poder ejercitar lo aprendido en cursos y tutoriales',
	buttonLabel: 'Start Now',
	imgStart: true,
	img: require('../../images/svg2.svg').default,
	alt: 'image',
	dark: true,
	primary: true,
	darkText: false,
	start: '',
}