export const homeObjOne = {
	id: 'about',
	lightBg: false,
	lightText: false,
	lightTextDesc: true,
	lightTextTop: true,
	topLine: 'Roperos, Multifunción, Aparador, Mesada, Bajo mesada, Linea Oficina y Dormitorios',
	headline: 'Te damos Solución a Todos los productos que buscas para renovar tú Hogar',
	description: '',
	buttonLabel: 'Contacto',
	imgStart: true,
	img: require('../../images/svg1.svg').default,
	alt: 'image',
	dark:true,
	primary: true,
	darkText: false,
	start: '',
}
export const homeObjTwo = {
	id: 'discover',
	lightBg: true,
	lightText: true,
	lightTextDesc: true,
	lightTextTop: true,
	topLine: 'Estamos para cubrir todas las necesidades de la region y brindar la mejor calidad',
	headline: 'Somos tendencia en el norte de Córdoba por nuestras ofertas y por nuestras atención',
	description: '',
	buttonLabel: 'Contacto',
	imgStart: false,
	img: require('../../images/svg2.svg').default,
	alt: 'Paper',
	dark: false,
	primary: false,
	darkText: false,
	start: 'true',
}
export const homeObjThree = {
	id: 'signup',
	lightBg: false,
	lightText: false,
	lightTextDesc: false,
	lightTextTop: false,
	topLine: '',
	headline: 'Nosotros y nuestra historia',
	description: 'Somos una pequeña empresa que fue creada en el año 2023 con la idea de ofrecer los productos más innovadores a la gente',
	buttonLabel: 'Inicio',
	imgStart: true,
	img: require('../../images/svg2.svg').default,
	alt: 'image',
	dark: true,
	primary: true,
	darkText: false,
	start: '',
}